export type Pet = {
  id: number
  photo: string
  status: 'lost' | 'found'
  type: string
  breed: string
  location: string
  date: string
  name: string
  age: string
  gender: string
  lastSeen?: string
  foundArea?: string
  description: string
  color: string
  size: string
  markings?: string
  behavior?: string
  health?: string
  contactName: string
  contactNumber: string
}

export const MOCK_PETS: Pet[] = [
  {
    id: 0,
    photo: "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=500&q=80",
    status: "found",
    type: "Dog",
    breed: "Golden Retriever",
    location: "Colombo",
    date: "2025-09-02",
    name: "Buddy",
    age: "Young",
    gender: "Male",
    foundArea: "Galle Face Green",
    description: "Friendly golden retriever found wandering around Galle Face Green. Wearing a blue collar but no identification tags.",
    color: "Golden",
    size: "Large",
    markings: "White patch on chest",
    behavior: "Very friendly and well-behaved",
    health: "Appears healthy and well-fed",
    contactName: "John Perera",
    contactNumber: "077-1234567"
  },
  {
    id: 1,
    photo: "https://images.unsplash.com/photo-1535241749838-299277b6305f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "lost",
    type: "Rabbit",
    breed: "Holland Lop",
    location: "Malabe",
    date: "2025-09-02",
    name: "Bunny",
    age: "Young",
    gender: "Female",
    lastSeen: "Near SLIIT Campus",
    description: "Sweet Holland Lop rabbit, mostly white with brown spots. Last seen hopping near the SLIIT campus garden area.",
    color: "White and Brown",
    size: "Small",
    markings: "Distinctive brown patches on back",
    behavior: "Gentle and shy",
    health: "Recently vaccinated, wearing a pink collar",
    contactName: "Sarah Silva",
    contactNumber: "077-9876543"
  },
  {
    id: 2,
    photo: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "found",
    type: "Turtle",
    breed: "Red-Eared Slider",
    location: "Nugegoda",
    date: "2025-09-02",
    name: "Shell",
    age: "Adult",
    gender: "Male",
    foundArea: "Delkanda Lake Area",
    description: "Healthy red-eared slider turtle found near Delkanda Lake. Very active and appears to be someone's pet.",
    color: "Green and Yellow",
    size: "Medium",
    markings: "Red patches near ears",
    behavior: "Active and friendly",
    health: "Good condition, well-maintained shell",
    contactName: "Amal Fernando",
    contactNumber: "077-5557777"
  },
  {
    id: 3,
    photo: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "found",
    type: "Hamster",
    breed: "Syrian",
    location: "Mount Lavinia",
    date: "2025-09-01",
    name: "Tiny",
    age: "Young",
    gender: "Male",
    foundArea: "Mount Lavinia Beach Park",
    description: "Found this adorable Syrian hamster in a carrier near the beach park. Very well-groomed and friendly.",
    color: "Golden Brown",
    size: "Small",
    markings: "White belly",
    behavior: "Playful and handleable",
    health: "Energetic and well-fed",
    contactName: "Maya Peris",
    contactNumber: "077-8889999"
  },
  {
    id: 4,
    photo: "https://images.unsplash.com/photo-1598974357801-cbca100e65d3?auto=format&fit=crop&w=500&q=80",
    status: "found",
    type: "Horse",
    breed: "Arabian",
    location: "Kandy",
    date: "2025-09-02",
    name: "Storm",
    age: "Adult",
    gender: "Male",
    foundArea: "Peradeniya Road",
    description: "Beautiful Arabian horse found wandering along Peradeniya Road. Well-trained and in excellent condition.",
    color: "White",
    size: "Large",
    markings: "Black mane and tail",
    behavior: "Calm and well-trained",
    health: "Excellent condition, recently shod",
    contactName: "Raj Mendis",
    contactNumber: "077-4445555"
  },
  {
    id: 5,
    photo: "https://images.unsplash.com/photo-1606567595334-d39972c85dbe?auto=format&fit=crop&w=500&q=80",
    status: "lost",
    type: "Bird",
    breed: "Love Bird",
    location: "Colombo",
    date: "2025-09-01",
    name: "Sky",
    age: "Young",
    gender: "Unknown",
    lastSeen: "Viharamahadevi Park",
    description: "Missing green and yellow love bird. Very friendly and responds to its name 'Sky'. Has a small yellow ring on right leg.",
    color: "Green and Yellow",
    size: "Small",
    markings: "Yellow ring on right leg",
    behavior: "Friendly, talks a little",
    health: "Good health, clipped wings",
    contactName: "Priya Dias",
    contactNumber: "077-3334444"
  },
  {
    id: 6,
    photo: "https://images.unsplash.com/photo-1591382386627-349b692688ff?auto=format&fit=crop&w=500&q=80",
    status: "lost",
    type: "Rabbit",
    breed: "Mini Rex",
    location: "Negombo",
    date: "2025-09-02",
    name: "Cotton",
    age: "Adult",
    gender: "Female",
    lastSeen: "Negombo Beach Road",
    description: "Lost Mini Rex rabbit with incredibly soft black fur. She's shy but friendly when approached slowly.",
    color: "Black",
    size: "Small",
    markings: "White spot under chin",
    behavior: "Shy but friendly",
    health: "Regular vet checks, spayed",
    contactName: "Lisa Fernando",
    contactNumber: "077-2223333"
  },
  {
    id: 7,
    photo: "https://images.unsplash.com/photo-1566251037378-5e04e3bec343?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "lost",
    type: "Horse",
    breed: "Mustang",
    location: "Chilaw",
    date: "2025-09-01",
    name: "Thunder",
    age: "Adult",
    gender: "Male",
    lastSeen: "Chilaw Beach Area",
    description: "Missing brown Mustang with black mane. Very gentle and responds to his name. Has a distinctive scar on right flank.",
    color: "Brown",
    size: "Large",
    markings: "Scar on right flank",
    behavior: "Gentle giant",
    health: "Excellent condition, needs daily medication",
    contactName: "Daniel Costa",
    contactNumber: "077-1112222"
  },
  {
    id: 8,
    photo: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "found",
    type: "Cat",
    breed: "Siamese",
    location: "Rajagiriya",
    date: "2025-09-02",
    name: "Luna",
    age: "Young",
    gender: "Female",
    foundArea: "Parliament Road",
    description: "Found this beautiful Siamese cat near Parliament Road. Very affectionate and well-cared for, clearly someone's beloved pet.",
    color: "Cream with brown points",
    size: "Medium",
    markings: "Traditional Siamese markings",
    behavior: "Very affectionate",
    health: "Healthy and well-groomed",
    contactName: "Nimal Perera",
    contactNumber: "077-6667777"
  },
  {
    id: 9,
    photo: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "lost",
    type: "Hamster",
    breed: "Roborovski",
    location: "Malabe",
    date: "2025-09-01",
    name: "Max",
    age: "Adult",
    gender: "Male",
    lastSeen: "Chandrika Kumaratunga Mawatha",
    description: "Lost tiny Roborovski hamster, very fast and small. Last seen near his cage in our garden. Responds to squeaking sounds.",
    color: "Sandy Brown",
    size: "Very Small",
    markings: "White eyebrows",
    behavior: "Quick and energetic",
    health: "Good health, needs special diet",
    contactName: "Kamala Silva",
    contactNumber: "077-8889999"
  },
  {
    id: 10,
    photo: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80",
    status: "found",
    type: "Cat",
    breed: "Maine Coon",
    location: "Kandy",
    date: "2025-09-02",
    name: "Shadow",
    age: "Young",
    gender: "Male",
    foundArea: "Kandy Lake Round",
    description: "Large Maine Coon cat found near Kandy Lake. Very distinctive long fur and friendly personality. Wearing a faded blue collar.",
    color: "Gray and White",
    size: "Large",
    markings: "Long fluffy tail",
    behavior: "Friendly and vocal",
    health: "Good condition, needs grooming",
    contactName: "Kumar Bandara",
    contactNumber: "077-4445555"
  },
  {
    id: 11,
    photo: "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=500&q=80",
    status: "lost",
    type: "Dog",
    breed: "Pug",
    location: "Dehiwala",
    date: "2025-09-02",
    name: "Charlie",
    age: "Adult",
    gender: "Male",
    lastSeen: "Dehiwala Zoo Area",
    description: "Missing friendly pug with a distinctive curly tail. Wearing a red collar with name tag. Has a slight limp in right front paw.",
    color: "Fawn",
    size: "Small",
    markings: "Black face mask",
    behavior: "Friendly, likes to snort",
    health: "Needs daily medication for joints",
    contactName: "James Wilson",
    contactNumber: "077-3334444"
  }
]